"use client";

import { useState, useEffect, useCallback } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Tabs } from "@/components/ui/Tabs";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Textarea } from "@/components/ui/Textarea";
import { Select } from "@/components/ui/Select";
import { getFingerprint } from "@/lib/utils/fingerprint";
import { cn } from "@/lib/utils/cn";
import toast from "react-hot-toast";
import Link from "next/link";
import {
  Languages,
  PenLine,
  ScanSearch,
  SpellCheck,
  Sparkles,
  Copy,
  BookmarkPlus,
  AlertCircle,
  Lock,
  CheckCircle,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

// ── Types ─────────────────────────────────────────────────────────────────────

type ToolType = "TRANSLATE" | "PARAPHRASE" | "AI_DETECT" | "GRAMMAR" | "HUMANIZE";

interface ToolResult {
  output: string;
  // GRAMMAR
  changes?: string[];
  // AI_DETECT
  score?: number;
  classification?: "AI Generated" | "Mixed Content" | "Human Written";
  configured?: boolean;
  // TRANSLATE
  targetLang?: string;
}

interface GuestUsageInfo {
  count: number;
  remaining: number;
  limit: number;
  exceeded: boolean;
}

// ── Tool definitions ──────────────────────────────────────────────────────────

const TOOLS: {
  id: ToolType;
  label: string;
  icon: React.ReactNode;
  description: string;
  requiresAuth?: boolean;
}[] = [
  {
    id: "TRANSLATE",
    label: "Translate",
    icon: <Languages size={15} />,
    description: "Translate academic text between English and Arabic while preserving terminology.",
  },
  {
    id: "PARAPHRASE",
    label: "Paraphrase",
    icon: <PenLine size={15} />,
    description: "Rewrite text with a stronger formal academic tone and enhanced clarity.",
  },
  {
    id: "AI_DETECT",
    label: "AI Detect",
    icon: <ScanSearch size={15} />,
    description: "Score the probability that a piece of text was generated by an AI model.",
  },
  {
    id: "GRAMMAR",
    label: "Grammar",
    icon: <SpellCheck size={15} />,
    description: "Correct grammar, spelling, punctuation, and academic-style issues.",
  },
  {
    id: "HUMANIZE",
    label: "Humanize",
    icon: <Sparkles size={15} />,
    description: "Refine AI-generated text to sound natural and authentically human-written.",
    requiresAuth: true,
  },
];

const LANG_OPTIONS = [
  { value: "en", label: "English" },
  { value: "ar", label: "Arabic" },
];

const MAX_WORDS = 1500;

// ── Helpers ───────────────────────────────────────────────────────────────────

function countWords(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function classificationColor(cls: string) {
  if (cls === "AI Generated") return "text-error";
  if (cls === "Mixed Content") return "text-warning";
  return "text-success";
}

function scoreBarColor(score: number) {
  if (score >= 70) return "bg-error";
  if (score >= 35) return "bg-warning";
  return "bg-success";
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default function ToolsPage() {
  const { data: session } = useSession();
  const router = useRouter();

  const [activeTool, setActiveTool] = useState<ToolType>("TRANSLATE");
  const [inputText, setInputText] = useState("");
  const [targetLang, setTargetLang] = useState<"en" | "ar">("en");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ToolResult | null>(null);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [fingerprint, setFingerprint] = useState("");
  const [guestUsage, setGuestUsage] = useState<GuestUsageInfo | null>(null);
  const [changesOpen, setChangesOpen] = useState(true);

  const wordCount = countWords(inputText);
  const overLimit = wordCount > MAX_WORDS;
  const currentTool = TOOLS.find((t) => t.id === activeTool)!;
  const isLockedForGuest = currentTool.requiresAuth && !session?.user;

  // ── Fingerprint + guest usage ────────────────────────────────────────────
  useEffect(() => {
    if (session?.user) return;
    getFingerprint().then((fp) => {
      setFingerprint(fp);
      fetch(`/api/guest/usage?fingerprint=${fp}`)
        .then((r) => r.json())
        .then((d: GuestUsageInfo) => setGuestUsage(d))
        .catch(() => null);
    });
  }, [session]);

  // Reset result when switching tools or clearing input
  const handleToolChange = useCallback((id: string) => {
    setActiveTool(id as ToolType);
    setResult(null);
    setSaved(false);
    setChangesOpen(true);
  }, []);

  // ── Run tool ─────────────────────────────────────────────────────────────
  const handleRun = async () => {
    if (!inputText.trim()) {
      toast.error("Please enter some text first.");
      return;
    }
    if (overLimit) {
      toast.error(`Text exceeds ${MAX_WORDS.toLocaleString()} words.`);
      return;
    }
    if (isLockedForGuest) {
      toast.error("Please sign in to use the Humanizer.");
      return;
    }
    if (!session?.user && guestUsage?.exceeded) {
      toast.error("Free usage limit reached. Sign up for unlimited access.");
      return;
    }

    setLoading(true);
    setResult(null);
    setSaved(false);

    try {
      const res = await fetch("/api/tools", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          toolType: activeTool,
          inputText,
          targetLang,
          fingerprint: session?.user ? undefined : fingerprint,
        }),
      });

      const data = await res.json() as ToolResult & { error?: string; limitReached?: boolean };

      if (!res.ok) {
        if (data.limitReached) {
          toast.error("Free limit reached. Sign up for unlimited access.", { duration: 5000 });
          setGuestUsage((prev) => (prev ? { ...prev, exceeded: true, remaining: 0 } : prev));
        } else {
          toast.error(data.error ?? "Something went wrong.");
        }
        return;
      }

      setResult(data);

      // Refresh guest usage counter
      if (!session?.user && fingerprint) {
        fetch(`/api/guest/usage?fingerprint=${fingerprint}`)
          .then((r) => r.json())
          .then((d: GuestUsageInfo) => setGuestUsage(d))
          .catch(() => null);
      }
    } catch {
      toast.error("Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  // ── Copy output ──────────────────────────────────────────────────────────
  const handleCopy = () => {
    if (!result?.output) return;
    navigator.clipboard.writeText(result.output).then(() => toast.success("Copied to clipboard."));
  };

  // ── Save to library ──────────────────────────────────────────────────────
  const handleSave = async () => {
    if (!result || !session?.user) return;
    setSaving(true);
    try {
      const metadata: Record<string, unknown> = {};
      if (activeTool === "TRANSLATE") metadata.targetLang = targetLang;
      if (activeTool === "AI_DETECT") {
        metadata.score = result.score;
        metadata.classification = result.classification;
      }
      if (activeTool === "GRAMMAR") metadata.changes = result.changes;

      const res = await fetch("/api/tools/save", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          toolType: activeTool,
          inputText,
          output: result.output,
          metadata,
        }),
      });

      if (!res.ok) {
        const d = await res.json() as { error?: string };
        toast.error(d.error ?? "Failed to save.");
        return;
      }

      setSaved(true);
      toast.success("Saved to your library.");
    } catch {
      toast.error("Network error. Please try again.");
    } finally {
      setSaving(false);
    }
  };

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <div className="flex flex-col min-h-screen bg-bg">
      <Navbar />

      <main className="flex-1 max-w-5xl mx-auto w-full px-4 sm:px-6 py-10">

        {/* ── Page header ── */}
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-[var(--text-primary)] mb-1">
            Research Tools
          </h1>
          <p className="text-sm text-[var(--text-secondary)]">
            AI-powered tools for academic writing — translation, paraphrasing, grammar, and more.
          </p>
        </div>

        {/* ── Tool tabs ── */}
        <Tabs
          tabs={TOOLS.map((t) => ({
            id: t.id,
            label: t.label,
            icon: t.requiresAuth && !session?.user
              ? <Lock size={13} className="text-[var(--text-secondary)]" />
              : t.icon,
          }))}
          active={activeTool}
          onChange={handleToolChange}
          className="mb-6"
        />

        {/* ── Tool description ── */}
        <p className="text-sm text-[var(--text-secondary)] mb-5">
          {currentTool.description}
        </p>

        {/* ── Guest limit warning ── */}
        {!session?.user && guestUsage && !guestUsage.exceeded && (
          <div className="flex items-center gap-2 mb-5 px-4 py-3 rounded-lg border border-[var(--border)] bg-[var(--surface)] text-sm text-[var(--text-secondary)]">
            <AlertCircle size={15} className="shrink-0 text-warning" />
            <span>
              {guestUsage.remaining} free use{guestUsage.remaining !== 1 ? "s" : ""} remaining.{" "}
              <Link href="/register" className="text-brand hover:underline font-medium">
                Sign up for unlimited access →
              </Link>
            </span>
          </div>
        )}

        {/* ── Limit exceeded banner ── */}
        {!session?.user && guestUsage?.exceeded && (
          <div className="flex items-center gap-3 mb-5 px-4 py-3 rounded-lg border border-error/30 bg-error/5 text-sm">
            <AlertCircle size={15} className="shrink-0 text-error" />
            <span className="text-error">
              Free limit reached.{" "}
              <Link href="/register" className="font-semibold underline">
                Create a free account
              </Link>{" "}
              for unlimited usage.
            </span>
          </div>
        )}

        {/* ── Main workspace ── */}
        <div className="grid lg:grid-cols-2 gap-5">

          {/* ─── Input panel ─── */}
          <Card className="flex flex-col gap-4 p-5">
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium text-[var(--text-primary)]">Input</span>
              <span
                className={cn(
                  "text-xs tabular-nums",
                  overLimit ? "text-error font-semibold" : "text-[var(--text-secondary)]"
                )}
              >
                {wordCount.toLocaleString()} / {MAX_WORDS.toLocaleString()} words
              </span>
            </div>

            <Textarea
              id="tool-input"
              placeholder={
                activeTool === "TRANSLATE"
                  ? "Paste your text here — source language is detected automatically…"
                  : activeTool === "AI_DETECT"
                  ? "Paste the text you want to analyse for AI content…"
                  : activeTool === "GRAMMAR"
                  ? "Paste your text here — all grammar and spelling errors will be corrected…"
                  : activeTool === "HUMANIZE"
                  ? "Paste AI-generated text here to make it sound human…"
                  : "Paste your academic text here…"
              }
              value={inputText}
              onChange={(e) => {
                setInputText(e.target.value);
                setResult(null);
                setSaved(false);
              }}
              className="min-h-[260px] text-sm resize-y"
            />

            {/* Translation language options */}
            {activeTool === "TRANSLATE" && (
              <Select
                id="target-lang"
                label="Translate to"
                value={targetLang}
                onChange={(e) => setTargetLang(e.target.value as "en" | "ar")}
                options={LANG_OPTIONS}
              />
            )}

            {/* Humanize lock overlay for guests */}
            {isLockedForGuest ? (
              <div className="flex flex-col items-center gap-2 py-4 text-center">
                <Lock size={20} className="text-[var(--text-secondary)]" />
                <p className="text-sm text-[var(--text-secondary)]">
                  The Humanizer is available to registered users.
                </p>
                <div className="flex gap-2 mt-1">
                  <Button size="sm" onClick={() => router.push("/register")}>
                    Sign up free
                  </Button>
                  <Button size="sm" variant="secondary" onClick={() => router.push("/login")}>
                    Log in
                  </Button>
                </div>
              </div>
            ) : (
              <Button
                onClick={handleRun}
                loading={loading}
                disabled={!inputText.trim() || overLimit || (!session?.user && guestUsage?.exceeded)}
                className="w-full"
              >
                {loading ? "Processing…" : `Run ${currentTool.label}`}
              </Button>
            )}
          </Card>

          {/* ─── Output panel ─── */}
          <Card className="flex flex-col gap-4 p-5">
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium text-[var(--text-primary)]">Output</span>
              {result && (
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-1.5 text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
                  >
                    <Copy size={13} />
                    Copy
                  </button>
                  {session?.user && !saved && (
                    <button
                      onClick={handleSave}
                      disabled={saving}
                      className="flex items-center gap-1.5 text-xs text-brand hover:text-brand-hover transition-colors disabled:opacity-50"
                    >
                      <BookmarkPlus size={13} />
                      {saving ? "Saving…" : "Save to Library"}
                    </button>
                  )}
                  {saved && (
                    <span className="flex items-center gap-1 text-xs text-success">
                      <CheckCircle size={13} />
                      Saved
                    </span>
                  )}
                </div>
              )}
            </div>

            {/* ── Empty / loading state ── */}
            {!result && !loading && (
              <div className="flex-1 flex items-center justify-center min-h-[260px] rounded-md border border-dashed border-[var(--border)]">
                <p className="text-sm text-[var(--text-secondary)]">
                  {isLockedForGuest
                    ? "Sign in to use this tool."
                    : "Your result will appear here."}
                </p>
              </div>
            )}

            {loading && (
              <div className="flex-1 flex flex-col items-center justify-center gap-3 min-h-[260px]">
                <svg
                  className="animate-spin h-7 w-7 text-brand"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                <p className="text-sm text-[var(--text-secondary)]">
                  {activeTool === "AI_DETECT" ? "Analysing content…" : "Generating response…"}
                </p>
              </div>
            )}

            {/* ── AI Detection: score visualisation ── */}
            {result && activeTool === "AI_DETECT" && (
              <div className="flex flex-col gap-5 min-h-[260px]">
                {!result.configured ? (
                  <div className="flex items-start gap-3 p-4 rounded-lg border border-warning/30 bg-warning/5">
                    <AlertCircle size={16} className="shrink-0 text-warning mt-0.5" />
                    <p className="text-sm text-[var(--text-secondary)]">{result.output}</p>
                  </div>
                ) : (() => {
                  // Safely extract score/classification with explicit fallbacks so
                  // SVG math never receives NaN and classificationColor never receives undefined.
                  const score = typeof result.score === "number" ? result.score : 0;
                  const classification = result.classification ?? "Human Written";
                  const circumference = 2 * Math.PI * 40;

                  return (
                    <>
                      {/* Score ring */}
                      <div className="flex flex-col items-center gap-2 pt-4">
                        <div className="relative w-28 h-28">
                          <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
                            <circle cx="50" cy="50" r="40" fill="none" stroke="var(--border)" strokeWidth="10" />
                            <circle
                              cx="50" cy="50" r="40" fill="none"
                              stroke={score >= 70 ? "var(--accent-error)" : score >= 35 ? "var(--accent-warning)" : "var(--accent-success)"}
                              strokeWidth="10"
                              strokeDasharray={`${circumference}`}
                              strokeDashoffset={`${circumference * (1 - score / 100)}`}
                              strokeLinecap="round"
                            />
                          </svg>
                          <div className="absolute inset-0 flex flex-col items-center justify-center">
                            <span className={cn("text-2xl font-bold", classificationColor(classification))}>
                              {score}%
                            </span>
                            <span className="text-[10px] text-[var(--text-secondary)]">AI probability</span>
                          </div>
                        </div>
                        <span className={cn("text-sm font-semibold", classificationColor(classification))}>
                          {classification}
                        </span>
                      </div>

                      {/* Score bar */}
                      <div className="space-y-1.5">
                        <div className="flex justify-between text-xs text-[var(--text-secondary)]">
                          <span>Human</span>
                          <span>AI</span>
                        </div>
                        <div className="h-2.5 rounded-full bg-[var(--border)] overflow-hidden">
                          <div
                            className={cn("h-full rounded-full transition-all duration-700", scoreBarColor(score))}
                            style={{ width: `${score}%` }}
                          />
                        </div>
                      </div>

                      <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
                        {result.output}
                      </p>
                    </>
                  );
                })()}
              </div>
            )}

            {/* ── Grammar: corrected text + changes list ── */}
            {result && activeTool === "GRAMMAR" && (
              <div className="flex flex-col gap-4 min-h-[260px]">
                <div
                  className="flex-1 rounded-md border border-[var(--border)] bg-[var(--bg)] px-4 py-3 text-sm text-[var(--text-primary)] whitespace-pre-wrap leading-relaxed overflow-auto"
                  style={{ minHeight: "160px" }}
                >
                  {result.output}
                </div>

                {Array.isArray(result.changes) && result.changes.length > 0 && (
                  <div className="border border-[var(--border)] rounded-md overflow-hidden">
                    <button
                      onClick={() => setChangesOpen((v) => !v)}
                      className="w-full flex items-center justify-between px-4 py-2.5 text-sm font-medium bg-[var(--surface)] hover:bg-[var(--border)] transition-colors"
                    >
                      <span className="flex items-center gap-2">
                        <CheckCircle size={14} className="text-success" />
                        {result.changes.length} correction{result.changes.length !== 1 ? "s" : ""} made
                      </span>
                      {changesOpen ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                    </button>
                    {changesOpen && (
                      <ul className="divide-y divide-[var(--border)]">
                        {result.changes.map((c, i) => (
                          <li key={i} className="flex items-start gap-2 px-4 py-2 text-xs text-[var(--text-secondary)]">
                            <span className="mt-0.5 text-success shrink-0">✓</span>
                            {c}
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                )}

                {Array.isArray(result.changes) && result.changes.length === 0 && (
                  <div className="flex items-center gap-2 text-sm text-success">
                    <CheckCircle size={15} />
                    No issues found — your text looks great!
                  </div>
                )}
              </div>
            )}

            {/* ── Default: plain text output (Translate, Paraphrase, Humanize) ── */}
            {result && !["AI_DETECT", "GRAMMAR"].includes(activeTool) && (
              <div
                className="flex-1 rounded-md border border-[var(--border)] bg-[var(--bg)] px-4 py-3 text-sm text-[var(--text-primary)] whitespace-pre-wrap leading-relaxed overflow-auto"
                style={{ minHeight: "260px" }}
              >
                {result.output}
              </div>
            )}
          </Card>
        </div>

        {/* ── Guest sign-up nudge (bottom) ── */}
        {!session?.user && (
          <p className="mt-6 text-center text-xs text-[var(--text-secondary)]">
            <Link href="/register" className="text-brand hover:underline">
              Create a free account
            </Link>{" "}
            for unlimited tool usage, saved history, and access to the Humanizer.
          </p>
        )}
      </main>

      <Footer />
    </div>
  );
}
